name: UnitTestForJavaSpringBoot

on: [push]

jobs:
  day3job:
    runs-on: ubuntu-latest

    env: 
      JAVA_VERSION: 17
      JAVA_DISTRIBUTION: temurin

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup JDK17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Build with Maven
        run: mvn clean install
      - name: Run unit tests
        run: mvn test
       
  
